replicaCount: 1
image:
  repository: docker.io/rotema/rickandmortyapi
  tag: "v1"
podAnnotations: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: rickandmortyapi.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []